# -*- coding: utf-8 -*-
"""Despliegue_Videojuegos_Regresion_Manual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12AcEcsLhkBIqp3Etk5nHPS6oBDIcm4gn

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-reg.pkl'
modelo, min_max_scaler, variables = pickle.load(open(filename, 'rb'))

#modelo

#Cargamos los datos futuros
#data = pd.read_csv("/content/videojuegos-datosFuturos (2).csv")
#data.head()

#Interfaz gráfica


#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de inversión en una tienda de videojuegos')

Edad = st.slider('Edad', min_value=14, max_value=52, value=20, step=1)
videojuego = st.selectbox('Videojuego', ["'Mass Effect'","'Battlefield'", "'Fifa'","'KOA: Reckoning'","'Crysis'","'Sim City'","'Dead Space'","'F1'"])
Plataforma = st.selectbox('Plataforma', ["'Play Station'", "'Xbox'","PC","Otros"])
Sexo = st.selectbox('Sexo', ['Hombre', 'Mujer'])
Consumidor_habitual = st.selectbox('Consumidor_habitual', ['True', 'False'])


#Dataframe
datos = [[Edad, videojuego,Plataforma,Sexo,Consumidor_habitual]]
data = pd.DataFrame(datos, columns=['Edad', 'videojuego','Plataforma','Sexo','Consumidor_habitual']) #Dataframe con los mismos nombres de variables

data.info()

#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['videojuego', 'Plataforma','Sexo', 'Consumidor_habitual'], drop_first=False, dtype=int)
data_preparada.head()

#EN LOS DESPLIEGUES NUNCA BORRAMOS DUMMIES, OSEA DROP FIRST SIEMPRE SIEMPRE SERÁ FALSO

data_preparada.info()

#Se adicionan las columnas faltantes
#Porque por dummies y otras cosas (varaibles sin registros) se perdieron algunas columnas so con reindex las llenamos asi sea a punta de cero
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red, SVM, Reg
#En los despliegues no se llama fit
#data_preparada[['Edad']]= min_max_scaler.transform(data_preparada[['Edad']])
#data_preparada.head()

"""#Predicciones"""

#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

data

# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 5% (mape: error porcentual)")
